config/routes.rb
Jobs::Application.routes.draw do 
  root 'home#index'
  get '/search' => 'jobs#search'
  match '/result' => 'jobs#result' , via: [:get, :post]
  get '/sobre_nos' => 'home#sobre_nos'
  get '/destaques' => 'jobs#featured'
  get '/servicos' => 'home#service'
  get '/contato' => 'contacts#new'
  get '/lista' => 'jobs#jobs_list'
  get '/perfil' => 'profiles#new'
  get '/phones' => 'phones#new'
  get '/endereco' => 'addresses#new'
  get '/informacao_pessoais' => 'applicants#new'
  get '/perfil_empresa' => 'customers#new'
  get 'termos_de_servico' => 'home#terms'

  resources :addresses
  resources :applicant_jobs
  resources :applicants
  resources :contacts
  resources :customers
  resources :jobs do 
    resources :applicant_jobs
  end
  resources :phones
  resources :profiles
 
  devise_for :users










end

app/models/applicant_job.rb
class ApplicantJob < ActiveRecord::Base
	belongs_to :job
	belongs_to :applicant 
end

app/controllers/applicant_jobs_controller.rb
class ApplicantJobsController < ApplicationController
  #before_action :search_job, only: [:create]
  before_action :set_applicant_job, only: [:show, :edit, :update, :destroy, :search_job]
  before_action :profile_complete, only: [:create, :new]
  respond_to :html

  def index
    @applicant_jobs = ApplicantJob.all
    respond_with(@applicant_jobs)
  end

  def show
    respond_with(@applicant_job)
  end

  def new
    @applicant_job = ApplicantJob.new
    respond_with(@applicant_job)
  end

  def edit
  end

  def create
  	@user = current_user
    @applicant_job = ApplicantJob.where(applicant_id: @user.applicant.id, job_id: applicant_job_params[:job_id]).limit(1)
       if @applicant_job.any?
          flash[:error] = 'Usuario ja cadastrado.'
          redirect_to jobs_path
       else

        @applicant_job = @user.applicant.applicant_jobs.build(applicant_job_params)

        @applicant_job.save
        
        redirect_to jobs_path
        #respond_with(@applicant_job)
       end
  end

  def update
    @applicant_job.update(applicant_job_params)
    respond_with(@applicant_job)
  end

  def destroy
    @applicant_job.destroy
    respond_with(@applicant_job)
  end

  def jobs_search
    @user = current_user
    @applicant_job = @user.applicant.applicant_jobs.build(applicant_job_params)
    @applicant_job.save
    respond_with(@applicant_job)
  end

  private
    def set_applicant_job
      @applicant_job = ApplicantJob.find(params[:id])
    end

    def search_job
        @user = current_user
      @applicant_job = ApplicantJob.where(applicant_id: @user.applicant.id, job_id: applicant_job_params[:job_id]).limit(1)
       if @applicant_job.empty?
          flash[:error] = 'Usuario ja cadastrado.'
          redirect_to jobs_path
       end
    end

    def profile_complete
     if current_user.applicant.nil?
        flash[:error] = 'Informações pessoais incompretas.'
        redirect_to jobs_path
     end
    end

    def applicant_job_params
      params.require(:applicant_job).permit(:applicant_id, :job_id)
    end
end

app/helpers/applicant_job_helper.rb
module ApplicantJobHelper
end

app/helpers/applicant_jobs_helper.rb
module ApplicantJobsHelper
end

app/views/applicant_jobs/_applicant_job.html.erb

<strong><%= @applicant_job %></strong>

app/views/applicant_jobs/_form.html.erb
<%= form_for @applicant_job, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :applicant_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :applicant_id, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :job_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :job_id, :class => 'form-control' %>
    </div>
  </div>
<br>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                applicant_jobs_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/applicant_jobs/edit.html.erb
<%- model_class = ApplicantJob -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applicant_jobs/index.html.erb
<%- model_class = ApplicantJob -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:applicant_id) %></th>
      <th><%= model_class.human_attribute_name(:job_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @applicant_jobs.each do |applicant_job| %>
      <tr>
        <td><%= link_to applicant_job.id, applicant_job_path(applicant_job) %></td>
        <td><%= applicant_job.applicant_id %></td>
        <td><%= applicant_job.job_id %></td>
        <td><%=l applicant_job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_applicant_job_path(applicant_job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      applicant_job_path(applicant_job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_applicant_job_path,
            :class => 'btn btn-primary' %>

app/views/applicant_jobs/new.html.erb
<%- model_class = ApplicantJob -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applicant_jobs/show.html.erb
<%- model_class = ApplicantJob -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:applicant_id) %>:</strong></dt>
  <dd><%= @applicant_job.applicant_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:job_id) %>:</strong></dt>
  <dd><%= @applicant_job.job_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              applicant_jobs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_applicant_job_path(@applicant_job), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              applicant_job_path(@applicant_job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>