config/routes.rb
Jobs::Application.routes.draw do 
  root 'home#index'
  get '/search' => 'jobs#search'
  match '/result' => 'jobs#result' , via: [:get, :post]
  get '/sobre_nos' => 'home#sobre_nos'
  get '/destaques' => 'jobs#featured'
  get '/servicos' => 'home#service'
  get '/contato' => 'contacts#new'
  get '/lista' => 'jobs#jobs_list'
  get '/perfil' => 'profiles#new'
  get '/phones' => 'phones#new'
  get '/endereco' => 'addresses#new'
  get '/informacao_pessoais' => 'applicants#new'
  get '/perfil_empresa' => 'customers#new'
  get 'termos_de_servico' => 'home#terms'

  resources :addresses
  resources :applicant_jobs
  resources :applicants
  resources :contacts
  resources :customers
  resources :jobs do 
    resources :applicant_jobs
  end
  resources :phones
  resources :profiles
 
  devise_for :users










end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :customer
	has_and_belongs_to_many :applicants, join_table: :applicants_jobs
	has_many :applicant_jobs #, through: :applicant
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
	def self.search(query)
		where("title LIKE :q", :q => "%#{query}%")
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  #before_action :set_job, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!
  before_action :jobs_checked, only: [:create, :new]
  #load_and_authorize_resource #:except => [:show, :index, :featured]
  
  #attr_accessor  :slug, :all
  #skip_authorize_resource :only => [:show, :index, :featured, :manifest]


  before_action :set_job, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, :except => [:index, :featured]
  #before_filter :authenticate_user!, :except => [:show, :index, :featured]
  load_and_authorize_resource :except => [:show, :index, :featured], param_method: :job_params
  skip_authorize_resource :only => [:index, :featured, :job, :result]
  attr_accessor :user_id, :all
  before_action :check_perfile, only: [:new, :jobs_list]
  respond_to :html

  def index
    #@jobs = Job.order(:title).page params[:page]
    @jobs = Job.page(params[:page]).per(6)
    #@applicant_job  = ApplicantJob.count(:job_id) #total de escritos 
    #if @applicant_job.any?
     # @applicant_job =1
   # end
   # @applicant_job  = ApplicantJob.all 
    @applicant_job  = ApplicantJob.count(:job_id)
    respond_with(@jobs, @applicant_job)
  end

  def show
    respond_with(@job)
  end

  def new
      @job = Job.new
      respond_with(@job)
  end

  def edit
  end

  def create
    #authorize! :create, @model
    @user = current_user
    @job = @user.customer.jobs.build(job_params)
    @job.save
    respond_with(@job)
  end

  def update
    @job.update(job_params)
    respond_with(@job)
  end

  def destroy
    @job.destroy
    respond_with(@job)
  end

  def search 
    
  end 

  def result
    @jobs = Job.page(params[:page]).per(6).search(params[:query])
    if @jobs.empty?
      flash[:error] = 'Não foi encontrado nenhum resultado.'
          redirect_to jobs_path
    else 
      respond_with (@jobs)
    end
    
  end
  
  def featured
     @jobs = Job.page(params[:page]).per(6).where({"featured" => true}) 
      if @jobs.empty?
          flash[:error] = 'Não foram encontradas nenhuma vaga em destaque.'
          redirect_to jobs_path
        else
           respond_with(@jobs)
      end
  end

  def jobs_list
      @jobs = Job.page(params[:page]).per(6).where({ :customer_id => current_user.customer.id }) 
      if @jobs.empty?
          flash[:error] = 'Não foram encontradas nenhuma vaga em sua lista.'
          redirect_to jobs_path
        else
           respond_with(@jobs)
      end
  end

  def job    
    @user = current_user
    @job = @user.applicant.build(job_params)
    @job.save
    respond_with(@job)
  end

  private

    def set_job
      @job = Job.friendly.find(params[:id])
    end

    def check_perfile
      if current_user.customer.nil?
      flash[:error] = 'O seu perfil esta incompreto.'
      redirect_to perfil_empresa_path
      end
    end
    def jobs_checked
      if current_user.customer.checked?
        flash[:error] = 'No momento sua conta não esta verificada.'
        redirect_to jobs_path
      end
    end
    def job_params
      params.require(:job).permit(:title, :vacancies, :salary, :expiration, :description, :current_user, :featured, :slug,:customer_id, :applicant_id, :jod_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vacancies, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :vacancies, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :salary, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :salary, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :expiration, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_field :expiration, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
  </div>
  <br>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                jobs_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/jobs/_jobs_index.html.erb
<%- model_class = Job -%>
  <%= paginate @jobs, :theme => 'twitter-bootstrap-3' %>
  <%# page_entries_info @jobs %>
    <% @jobs.each do |job| %>
    
        <%# link_to job.id, job_path(job) %>
          <div class="well">
            <h3 class= "txtleft"><%= job.title %></h3>
            <p class = "txtleft"><strong>Descrição: </strong> <%= job.description %></p>
            <p class= "txtleft"><strong>Número de vagas: </strong> <%= job.vacancies %></p>
            <p class = "txtleft"><strong>Sálario: </strong> <%= job.salary %></p>
            <p class = "txtleft"><strong>Validade: </strong> <%= job.expiration %></p>
          
          <%# button_to "Registrar enterece", action: "manifest" %>
            <%# if current_user.try(:admin?) || current_user.try(:customer?) %>
            
            <%# link_to t('.manifest', :default => t("helpers.links.manifest")), 
                          cadidatar_path, :class => 'btn btn-mini' %>

                          <%# render job.applicant_jobs %>
            <% if can? :create, ApplicantJob %>
                          <br>
                <p>Numero de escritos: </p>
                  <%= render job.applicant_jobs %> 
                  <%= form_for([job, job.applicant_jobs.build]) do |f| %>
                  <div class="control-group">
                    <div class="controls">
                      <%= f.hidden_field :job_id, :class => 'hidden_field' %>
                    </div>
                  </div>
                  <%# submit_tag "Cadastrar" %>

                  <div class="form-actions">
                  <%= f.submit nil, :class => 'btn btn-primary' %>
                  <%# link_to t('.cancel', :default => t("helpers.links.cancel")),
                        applicant_jobs_path, :class => 'btn' %>
                  </div>
                  <% end %>
          <% end %>


           <% if can? :update, job %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_job_path(job), :class => 'btn btn-mini' %> <% end %>
                          <% if can? :destroy, job %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          job_path(job),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %> <% end %>
                          <%#if can? :create, @job  if current_user.try(:admin?) || %>
<% if can? :create, job %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-mini btn-primary' %>
<% end %>
            <br>
            <% #end %>
          </div>
    <% end %>
<%= paginate @jobs, :theme => 'twitter-bootstrap-3' %>

  

app/views/jobs/_search.html.erb
   <div class='navbar-form navbar-left' role='search'>
      <%= form_tag result_path, :method => 'post' do %>
      <div class="form-group">
        <%= text_field_tag :query, params[:query], :class=>'form-control', :placeholder=>'Digite sua Pesquisa'  %>
      </div>
      <%= submit_tag "Pesquisar", :title => nil, :class=>'btn btn-default' %>
      <% end %>
   </div>

app/views/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/featured.html.erb
 <%= render :partial => 'jobs_index' %>

app/views/jobs/index.html.erb
		 <%= render :partial => 'jobs_index' %>

app/views/jobs/jobs_list.html.erb
 <%= render :partial => 'jobs_index' %>

app/views/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/result.html.erb
	 <%= render :partial => 'jobs_index' %>


app/views/jobs/show.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @job.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vacancies) %>:</strong></dt>
  <dd><%= @job.vacancies %></dd>
  <dt><strong><%= model_class.human_attribute_name(:salary) %>:</strong></dt>
  <dd><%= @job.salary %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expiration) %>:</strong></dt>
  <dd><%= @job.expiration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @job.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_id) %>:</strong></dt>
  <dd><%= @job.customer_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              jobs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_path(@job), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              job_path(@job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>