config/routes.rb
Jobs::Application.routes.draw do 
  root 'home#index'
  get '/search' => 'jobs#search'
  match '/result' => 'jobs#result' , via: [:get, :post]
  get '/sobre_nos' => 'home#sobre_nos'
  get '/destaques' => 'jobs#featured'
  get '/servicos' => 'home#service'
  get '/contato' => 'contacts#new'
  get '/lista' => 'jobs#jobs_list'
  get '/perfil' => 'profiles#new'
  get '/phones' => 'phones#new'
  get '/endereco' => 'addresses#new'
  get '/informacao_pessoais' => 'applicants#new'
  get '/perfil_empresa' => 'customers#new'
  get 'termos_de_servico' => 'home#terms'

  resources :addresses
  resources :applicant_jobs
  resources :applicants
  resources :contacts
  resources :customers
  resources :jobs do 
    resources :applicant_jobs
  end
  resources :phones
  resources :profiles
 
  devise_for :users










end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities 
   user ||= User.new
                             if user.admin? #|| user.is? :admin
                                can :manage, :all#, :id => user.id
                                can :assign_roles, User if user.admin?
                                can :manage, :all if user.is? :admin
                                
                               
                                #can [:destroy], Job do |j| 
                                  #j.customer.user == user
                                #end
                                #can :read, Job
                            
    ## => 

          elsif user.is? :applicant
                can [:update,:destroy, :read], [Applicant, Phone, Address] do |j|     
                                   j.user == user
                                end
                 can [:create], [Applicant, Phone, Profile, Address, ApplicantJob] if user.is? :applicant
                    
                        can [:update,:destroy, :read], [Profile, ApplicantJob] do |j| 
                                   j.applicant.user == user
                                end

           elsif user.is? :customer
                can [:destroy, :update] , Job, :id => user.id #, :customer_id => user.customer.id    # Foi foda cancan do capeta
                can :create, [Job, Address, Phone, Customer] if user.is? :customer
                can [:update,:destroy, :read], [Customer, Phone, Address] do |j|     
                                   j.user == user
                                end
                can :jobs_list, Job if user.is? :customer
            else
    
       
                          
                        can :read, [Job] if user.is? [:default]
                            cannot :manage, :all if user.is? :banned
                                #can :read Job, if user.nil?
              end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
    belongs_to :user
	has_one :profile, :dependent => :destroy
	has_and_belongs_to_many :jobs, join_table: :applicants_jobs
	has_many :applicant_jobs
	extend FriendlyId
  	friendly_id :first_name, use: :slugged
end

app/models/applicant_job.rb
class ApplicantJob < ActiveRecord::Base
	belongs_to :job
	belongs_to :applicant 
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :nome,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :mensagem
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "joelcio_ms@hotmail.com",
      :from => %("#{nome}" <#{email}>)
    }
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
       
	belongs_to :user
	#has_many :address, :dependent => :destroy
	has_many :jobs, :dependent => :destroy
	
	validates :user_id, :uniqueness => true
	extend FriendlyId
  	friendly_id :trading_name, use: :slugged

end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :customer
	has_and_belongs_to_many :applicants, join_table: :applicants_jobs
	has_many :applicant_jobs #, through: :applicant
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
	def self.search(query)
		where("title LIKE :q", :q => "%#{query}%")
	end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
	belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :applicant
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #attr_accessor :email, :password, :password_confirmation, :remember_me, :username
  apply_simple_captcha
  # User::Roles
  # The available roles
  #Roles = [ :admin , :applicant, :customer, :default ]
  ROLES = %w[admin customer applicant moderator author default banned]

  #Roles #
  #1 = admin	
  #2 = customer
  #3 = author
  #4 = 
  #5 = moderator
  # 	#
  attr_accessor :login
   # :on takes an array as well

  has_one :customer
	has_one :applicant
	has_one :phone, :dependent => :destroy
	has_one :address, :dependent => :destroy
	has_many :jobs, through: :customer
	has_one :profile, through: :applicant
  has_many :applicant_jobs, through: :job
  has_many :applicant_jobs, through: :applicant

  	  #validates_uniqueness_of :username
	  #validates_presence_of :username
	  validates :username, :presence => true, :uniqueness => true, :format => /[a-z]/

	  validates :username, length: { in: 4..20 }


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
####


              			# in models/user.rb
              def roles=(roles)
                self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
              end

              def roles
                ROLES.reject do |r|
                  ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
                end
              end

              # in models/user.rb
              def is?(role)
                roles.include?(role.to_s)
              end

         	def self.find_for_database_authentication(warden_conditions)
		      conditions = warden_conditions.dup
		      if login = conditions.delete(:login)
		        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
		      else
		        where(conditions.to_h).first
		      end
		    end

		  protected

		  def configure_permitted_parameters
		    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :username, roles: [])}
		  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def ads1
  end

  def ads2
  end

  def ads3
  end

  def ads4
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container"> 
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
             <a class="navbar-brand" href="/"><i class="fa fa-paper-plane"></i>Inicio</a>
          </div>
          <div class='navbar-form navbar-left' role='search'>
              <%= form_tag result_path, :method => 'post' do %>
              <div class="form-group">
                <%= text_field_tag :query, params[:query], :class=>'form-control', :placeholder=>'Digite sua Pesquisa'  %>
              </div>
              <div class="form-group">
              <%= submit_tag "Pesquisar", :title => nil, :class=>'btn btn-default' %>
              </div>
              <% end %>
           </div>
          <div id="navbar" class="navbar-collapse collapse in" aria-expanded="true" style="">
          <div class="menu">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Oportunidades<span class="caret"></span></a>
                          <ul class="dropdown-menu" role="menu">
                            <li><%= link_to "Vagas", jobs_path %></li>
                            <li><%= link_to "Vagas em destaque", destaques_path %></li>
                          </ul>
              </li>
              <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Perfil<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
              
              <% if can? :create, Job %>
                <li class="divider"></li>
                <li class="dropdown-header">Jobs</li>
                <li><%= link_to "Nova Opotunidade", new_job_path %></li>
              <% end %>
              
              <% if can? :jobs_list, Job %>
                <li><%= link_to "Minhas vagas postadas", lista_path %></li>
                <li class="divider"></li>
              <% end %>
                  <li class="divider"></li>
                  <li class="dropdown-header">Perfil</li>
                <% if current_user.try(:admin?) %>
                    <li><%= link_to "Perfil da empresa", perfil_empresa_path %></li>
                <% else %>
                    <% if can? :create, Customer %>
                      <li><%= link_to "Perfil da empresa", perfil_empresa_path %></li>
                    <% end %>
                    <% if can? :create, Applicant %>
                      <li><%= link_to "Informações pessoais", informacao_pessoais_path %></li>
                    <% end %>
                <% end %>
              <% if can? :create, Profile %>
                <li><%= link_to "Prefil e Habilidades", perfil_path %></li>
              <% end %>
              <% if can? :create, Phone %>
                <li><%= link_to "Telefones", phones_path %></li>
              <% end %>
              <% if can? :create, Address %>
                <li><%= link_to "Endereço", endereco_path %></li>
              <% end %>
                </ul>
              </li>
              <% end %>
                  <li><%= link_to "Serviços", servicos_path %></li>
                  <li><%= link_to "Contato", contato_path %></li>
                  <li><%= link_to "Sobre nós", sobre_nos_path %></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true"><span class="fa fa-user" aria-hidden="true"></span><strong><%= current_user.username %></strong><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li> <%= link_to 'Editar dados de acesso', edit_user_registration_path, :class => 'navbar-link' %></li>
                  <li><%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                </ul>
                </li>
              <% else %>
             <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true"><span class="fa fa-user" aria-hidden="true"></span>Mais..<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Registrar", new_user_registration_path, :class => 'navbar-link'  %></li>
                  <li><%= link_to "Entrar", new_user_session_path, :class => 'navbar-link'  %></li>
                </ul>
                </li>
              <% end %>
              
            </ul>
          </div><!--/.nav-collapse -->
         </div>
        </div><!--/.container-fluid -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jobs" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%# stylesheet_link_tag "bootstrap.min", :media => "all" %>
    <%# stylesheet_link_tag "flexslider", :media => "all" %>
    <%# stylesheet_link_tag "style", :media => "all" %>
    <%# stylesheet_link_tag "font-awesome.min", :media => "all" %>
    <%# javascript_include_tag "jquery.min" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
<!-- Fim -->
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900' rel='stylesheet' type='text/css'>

<!--Fim menu-->
      <%= render :partial => 'layouts/navbar' %>
<!--

-->
     <div class=" main">
          <!--

        -->
  <% if user_signed_in? %>

  <!-- precisaa ???-->

      <div class="container">
        <div class="col-xs-6 col-md-3">
          <div class="list-group">
             <a href="#" class="list-group-item list-group-item-success"><strong>Munu</strong></a>
              <% if can? :create, Job %>
               
               <%= link_to "Nova Opotunidade", new_job_path,:class=>'list-group-item' %>
              <% end %>
              
              <% if can? :jobs_list, Job %>
                <%= link_to "Minhas vagas postadas", lista_path,:class=>'list-group-item' %>
              <% end %>
                  <a href="#" class="list-group-item list-group-item-success"><strong>Perfil</strong></a>
                 
                <% if current_user.try(:admin?) %>
                    <%= link_to "Perfil da empresa", perfil_empresa_path,:class=>'list-group-item' %>
                <% else %>
                    <% if can? :create, Customer %>
                     <%= link_to "Perfil da empresa", perfil_empresa_path,:class=>'list-group-item' %>
                    <% end %>
                    <% if can? :create, Applicant %>
                      <%= link_to "Informações pessoais", informacao_pessoais_path,:class=>'list-group-item' %>
                    <% end %>
                <% end %>
              <% if can? :create, Profile %>
               <%= link_to "Prefil e Habilidades", perfil_path,:class=>'list-group-item' %>
              <% end %>
              <% if can? :create, Phone %>
                <%= link_to "Telefones", phones_path,:class=>'list-group-item' %>
              <% end %>
              <% if can? :create, Address %>
                <%= link_to "Endereço", endereco_path,:class=>'list-group-item'%>
              <% end %>
          </div><!--/.well -->
      </div>
   <div class="col-xs-6 col-md-6">
     <% else %>
     <div class="container">
        <%= render :partial => 'ads/ads' %>
        <div class="col-xs-6 col-md-6">
          <% end %>
     
        <!--/span == cols -->

        <!--

          --> 
          <%= bootstrap_flash %>
                <%= yield %>
        <!-- 

        -->
    </div>

    <%# if user_signed_in? %>

           <%= render :partial => 'ads/ads' %>
    <%# end %>
  </div>
<hr>
<!-- Fim content-->



<!--fim serviços-->
<div class="footer">
  <div class="footer_bottom">
    <div class="follow-us"> <a class="fa fa-facebook social-icon" href="#"></a> <a class="fa fa-twitter social-icon" href="#"></a> <a class="fa fa-linkedin social-icon" href="#"></a> <a class="fa fa-google-plus social-icon" href="#"></a> </div>
    <div class="copy">
      <p>Copyright &copy; 2015 Company Name. Design by <a href="http://www.systemdesigner.com.br" rel="nofollow">SystemDesigner</a></p>
    </div>
  </div>
</div>

<%# javascript_include_tag "bootstrap.min.js" %>
<%# javascript_include_tag "jquery.flexslider.js" %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jobs" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%# stylesheet_link_tag "bootstrap.min", :media => "all" %>
    <%# stylesheet_link_tag "flexslider", :media => "all" %>
    <%# stylesheet_link_tag "style", :media => "all" %>
    <%# stylesheet_link_tag "font-awesome.min", :media => "all" %>
    <%# javascript_include_tag "jquery.min" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
<!-- Fim -->
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900' rel='stylesheet' type='text/css'>
</head>
<!-- final head -->
<body>
<%= render :partial => 'layouts/navbar' %>
<!--Fim menu-->
  <div class=" main">
          <!---->
     
        <!--/span == cols -->

        <!----> 
          <%= bootstrap_flash %>
                <%= yield %>
        <!---->
    
  </div>
<hr>
<!-- Fim content-->



<!--fim serviços-->
<div class="footer">
  <div class="footer_bottom">
    <div class="follow-us"> <a class="fa fa-facebook social-icon" href="#"></a> <a class="fa fa-twitter social-icon" href="#"></a> <a class="fa fa-linkedin social-icon" href="#"></a> <a class="fa fa-google-plus social-icon" href="#"></a> </div>
    <div class="copy">
      <p>Copyright &copy; 2015 Company Name. Design by <a href="http://www.systemdesigner.com.br" rel="nofollow">SystemDesigner</a></p>
    </div>
  </div>
</div>
</div>
<%# javascript_include_tag "bootstrap.min.js" %>
<%# javascript_include_tag "jquery.flexslider.js" %>
</body>
</html>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>